// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClusterMessages.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Akka.Cluster.Protobuf.Msg {

  /// <summary>Holder for reflection information generated from ClusterMessages.proto</summary>
  public static partial class ClusterMessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for ClusterMessages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClusterMessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVDbHVzdGVyTWVzc2FnZXMucHJvdG8SGUFra2EuQ2x1c3Rlci5Qcm90b2J1",
            "Zi5Nc2cidAoHV2VsY29tZRI2CgRmcm9tGAEgASgLMiguQWtrYS5DbHVzdGVy",
            "LlByb3RvYnVmLk1zZy5VbmlxdWVBZGRyZXNzEjEKBmdvc3NpcBgCIAEoCzIh",
            "LkFra2EuQ2x1c3Rlci5Qcm90b2J1Zi5Nc2cuR29zc2lwIpgBCg5Hb3NzaXBF",
            "bnZlbG9wZRI2CgRmcm9tGAEgASgLMiguQWtrYS5DbHVzdGVyLlByb3RvYnVm",
            "Lk1zZy5VbmlxdWVBZGRyZXNzEjQKAnRvGAIgASgLMiguQWtrYS5DbHVzdGVy",
            "LlByb3RvYnVmLk1zZy5VbmlxdWVBZGRyZXNzEhgKEHNlcmlhbGl6ZWRHb3Nz",
            "aXAYAyABKAwikgEKDEdvc3NpcFN0YXR1cxI2CgRmcm9tGAEgASgLMiguQWtr",
            "YS5DbHVzdGVyLlByb3RvYnVmLk1zZy5VbmlxdWVBZGRyZXNzEhEKCWFsbEhh",
            "c2hlcxgCIAMoCRI3Cgd2ZXJzaW9uGAMgASgLMiYuQWtrYS5DbHVzdGVyLlBy",
            "b3RvYnVmLk1zZy5WZWN0b3JDbG9jayKyAQoGR29zc2lwEjIKB21lbWJlcnMY",
            "ASADKAsyIS5Ba2thLkNsdXN0ZXIuUHJvdG9idWYuTXNnLk1lbWJlchI7Cghv",
            "dmVydmlldxgCIAEoCzIpLkFra2EuQ2x1c3Rlci5Qcm90b2J1Zi5Nc2cuR29z",
            "c2lwT3ZlcnZpZXcSNwoHdmVyc2lvbhgDIAEoCzImLkFra2EuQ2x1c3Rlci5Q",
            "cm90b2J1Zi5Nc2cuVmVjdG9yQ2xvY2sihwEKDkdvc3NpcE92ZXJ2aWV3EjYK",
            "BHNlZW4YASADKAsyKC5Ba2thLkNsdXN0ZXIuUHJvdG9idWYuTXNnLlVuaXF1",
            "ZUFkZHJlc3MSPQoMcmVhY2hhYmlsaXR5GAIgASgLMicuQWtrYS5DbHVzdGVy",
            "LlByb3RvYnVmLk1zZy5SZWFjaGFiaWxpdHki+gEKDFJlYWNoYWJpbGl0eRIy",
            "CgdyZWNvcmRzGAEgAygLMiEuQWtrYS5DbHVzdGVyLlByb3RvYnVmLk1zZy5S",
            "ZWNvcmQSTQoIdmVyc2lvbnMYAiADKAsyOy5Ba2thLkNsdXN0ZXIuUHJvdG9i",
            "dWYuTXNnLlJlYWNoYWJpbGl0eS5SZWFjaGFiaWxpdHlWZXJzaW9uGmcKE1Jl",
            "YWNoYWJpbGl0eVZlcnNpb24SPwoNdW5pcXVlQWRkcmVzcxgBIAEoCzIoLkFr",
            "a2EuQ2x1c3Rlci5Qcm90b2J1Zi5Nc2cuVW5pcXVlQWRkcmVzcxIPCgd2ZXJz",
            "aW9uGAIgASgDIpwCCgZSZWNvcmQSOgoIb2JzZXJ2ZXIYASABKAsyKC5Ba2th",
            "LkNsdXN0ZXIuUHJvdG9idWYuTXNnLlVuaXF1ZUFkZHJlc3MSOQoHc3ViamVj",
            "dBgCIAEoCzIoLkFra2EuQ2x1c3Rlci5Qcm90b2J1Zi5Nc2cuVW5pcXVlQWRk",
            "cmVzcxJECgZzdGF0dXMYAyABKA4yNC5Ba2thLkNsdXN0ZXIuUHJvdG9idWYu",
            "TXNnLlJlY29yZC5SZWFjaGFiaWxpdHlTdGF0dXMSDwoHdmVyc2lvbhgEIAEo",
            "AyJEChJSZWFjaGFiaWxpdHlTdGF0dXMSDQoJUmVhY2hhYmxlEAASDwoLVW5y",
            "ZWFjaGFibGUQARIOCgpUZXJtaW5hdGVkEAIigAIKBk1lbWJlchI/Cg11bmlx",
            "dWVBZGRyZXNzGAEgASgLMiguQWtrYS5DbHVzdGVyLlByb3RvYnVmLk1zZy5V",
            "bmlxdWVBZGRyZXNzEhAKCHVwTnVtYmVyGAIgASgFEj4KBnN0YXR1cxgDIAEo",
            "DjIuLkFra2EuQ2x1c3Rlci5Qcm90b2J1Zi5Nc2cuTWVtYmVyLk1lbWJlclN0",
            "YXR1cxINCgVyb2xlcxgEIAMoCSJUCgxNZW1iZXJTdGF0dXMSCwoHSm9pbmlu",
            "ZxAAEgYKAlVwEAESCwoHTGVhdmluZxACEgsKB0V4aXRpbmcQAxIICgREb3du",
            "EAQSCwoHUmVtb3ZlZBAFInsKC1ZlY3RvckNsb2NrEkAKCHZlcnNpb25zGAEg",
            "AygLMi4uQWtrYS5DbHVzdGVyLlByb3RvYnVmLk1zZy5WZWN0b3JDbG9jay5W",
            "ZXJzaW9uGioKB1ZlcnNpb24SDAoEbm9kZRgBIAEoCRIRCgl0aW1lc3RhbXAY",
            "AiABKAMiSwoHQWRkcmVzcxIOCgZzeXN0ZW0YASABKAkSEAoIaG9zdG5hbWUY",
            "AiABKAkSDAoEcG9ydBgDIAEoBRIQCghwcm90b2NvbBgEIAEoCSJRCg1Vbmlx",
            "dWVBZGRyZXNzEjMKB2FkZHJlc3MYASABKAsyIi5Ba2thLkNsdXN0ZXIuUHJv",
            "dG9idWYuTXNnLkFkZHJlc3MSCwoDdWlkGAIgASgNQgJIAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Protobuf.Msg.Welcome), global::Akka.Cluster.Protobuf.Msg.Welcome.Parser, new[]{ "From", "Gossip" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Protobuf.Msg.GossipEnvelope), global::Akka.Cluster.Protobuf.Msg.GossipEnvelope.Parser, new[]{ "From", "To", "SerializedGossip" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Protobuf.Msg.GossipStatus), global::Akka.Cluster.Protobuf.Msg.GossipStatus.Parser, new[]{ "From", "AllHashes", "Version" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Protobuf.Msg.Gossip), global::Akka.Cluster.Protobuf.Msg.Gossip.Parser, new[]{ "Members", "Overview", "Version" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Protobuf.Msg.GossipOverview), global::Akka.Cluster.Protobuf.Msg.GossipOverview.Parser, new[]{ "Seen", "Reachability" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Protobuf.Msg.Reachability), global::Akka.Cluster.Protobuf.Msg.Reachability.Parser, new[]{ "Records", "Versions" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Protobuf.Msg.Reachability.Types.ReachabilityVersion), global::Akka.Cluster.Protobuf.Msg.Reachability.Types.ReachabilityVersion.Parser, new[]{ "UniqueAddress", "Version" }, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Protobuf.Msg.Record), global::Akka.Cluster.Protobuf.Msg.Record.Parser, new[]{ "Observer", "Subject", "Status", "Version" }, null, new[]{ typeof(global::Akka.Cluster.Protobuf.Msg.Record.Types.ReachabilityStatus) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Protobuf.Msg.Member), global::Akka.Cluster.Protobuf.Msg.Member.Parser, new[]{ "UniqueAddress", "UpNumber", "Status", "Roles" }, null, new[]{ typeof(global::Akka.Cluster.Protobuf.Msg.Member.Types.MemberStatus) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Protobuf.Msg.VectorClock), global::Akka.Cluster.Protobuf.Msg.VectorClock.Parser, new[]{ "Versions" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Protobuf.Msg.VectorClock.Types.Version), global::Akka.Cluster.Protobuf.Msg.VectorClock.Types.Version.Parser, new[]{ "Node", "Timestamp" }, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Protobuf.Msg.Address), global::Akka.Cluster.Protobuf.Msg.Address.Parser, new[]{ "System", "Hostname", "Port", "Protocol" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Protobuf.Msg.UniqueAddress), global::Akka.Cluster.Protobuf.Msg.UniqueAddress.Parser, new[]{ "Address", "Uid" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  /// Welcome, reply to Join
  /// </summary>
  public sealed partial class Welcome : pb::IMessage<Welcome> {
    private static readonly pb::MessageParser<Welcome> _parser = new pb::MessageParser<Welcome>(() => new Welcome());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Welcome> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Protobuf.Msg.ClusterMessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Welcome() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Welcome(Welcome other) : this() {
      From = other.from_ != null ? other.From.Clone() : null;
      Gossip = other.gossip_ != null ? other.Gossip.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Welcome Clone() {
      return new Welcome(this);
    }

    /// <summary>Field number for the "from" field.</summary>
    public const int FromFieldNumber = 1;
    private global::Akka.Cluster.Protobuf.Msg.UniqueAddress from_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.UniqueAddress From {
      get { return from_; }
      set {
        from_ = value;
      }
    }

    /// <summary>Field number for the "gossip" field.</summary>
    public const int GossipFieldNumber = 2;
    private global::Akka.Cluster.Protobuf.Msg.Gossip gossip_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.Gossip Gossip {
      get { return gossip_; }
      set {
        gossip_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Welcome);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Welcome other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(From, other.From)) return false;
      if (!object.Equals(Gossip, other.Gossip)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (from_ != null) hash ^= From.GetHashCode();
      if (gossip_ != null) hash ^= Gossip.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (from_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(From);
      }
      if (gossip_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Gossip);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (from_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(From);
      }
      if (gossip_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Gossip);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Welcome other) {
      if (other == null) {
        return;
      }
      if (other.from_ != null) {
        if (from_ == null) {
          from_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
        }
        From.MergeFrom(other.From);
      }
      if (other.gossip_ != null) {
        if (gossip_ == null) {
          gossip_ = new global::Akka.Cluster.Protobuf.Msg.Gossip();
        }
        Gossip.MergeFrom(other.Gossip);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (from_ == null) {
              from_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
            }
            input.ReadMessage(from_);
            break;
          }
          case 18: {
            if (gossip_ == null) {
              gossip_ = new global::Akka.Cluster.Protobuf.Msg.Gossip();
            }
            input.ReadMessage(gossip_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///*
  /// Gossip Envelope
  /// </summary>
  public sealed partial class GossipEnvelope : pb::IMessage<GossipEnvelope> {
    private static readonly pb::MessageParser<GossipEnvelope> _parser = new pb::MessageParser<GossipEnvelope>(() => new GossipEnvelope());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GossipEnvelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Protobuf.Msg.ClusterMessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GossipEnvelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GossipEnvelope(GossipEnvelope other) : this() {
      From = other.from_ != null ? other.From.Clone() : null;
      To = other.to_ != null ? other.To.Clone() : null;
      serializedGossip_ = other.serializedGossip_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GossipEnvelope Clone() {
      return new GossipEnvelope(this);
    }

    /// <summary>Field number for the "from" field.</summary>
    public const int FromFieldNumber = 1;
    private global::Akka.Cluster.Protobuf.Msg.UniqueAddress from_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.UniqueAddress From {
      get { return from_; }
      set {
        from_ = value;
      }
    }

    /// <summary>Field number for the "to" field.</summary>
    public const int ToFieldNumber = 2;
    private global::Akka.Cluster.Protobuf.Msg.UniqueAddress to_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.UniqueAddress To {
      get { return to_; }
      set {
        to_ = value;
      }
    }

    /// <summary>Field number for the "serializedGossip" field.</summary>
    public const int SerializedGossipFieldNumber = 3;
    private pb::ByteString serializedGossip_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString SerializedGossip {
      get { return serializedGossip_; }
      set {
        serializedGossip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GossipEnvelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GossipEnvelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(From, other.From)) return false;
      if (!object.Equals(To, other.To)) return false;
      if (SerializedGossip != other.SerializedGossip) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (from_ != null) hash ^= From.GetHashCode();
      if (to_ != null) hash ^= To.GetHashCode();
      if (SerializedGossip.Length != 0) hash ^= SerializedGossip.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (from_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(From);
      }
      if (to_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(To);
      }
      if (SerializedGossip.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(SerializedGossip);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (from_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(From);
      }
      if (to_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(To);
      }
      if (SerializedGossip.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SerializedGossip);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GossipEnvelope other) {
      if (other == null) {
        return;
      }
      if (other.from_ != null) {
        if (from_ == null) {
          from_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
        }
        From.MergeFrom(other.From);
      }
      if (other.to_ != null) {
        if (to_ == null) {
          to_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
        }
        To.MergeFrom(other.To);
      }
      if (other.SerializedGossip.Length != 0) {
        SerializedGossip = other.SerializedGossip;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (from_ == null) {
              from_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
            }
            input.ReadMessage(from_);
            break;
          }
          case 18: {
            if (to_ == null) {
              to_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
            }
            input.ReadMessage(to_);
            break;
          }
          case 26: {
            SerializedGossip = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///*
  /// Gossip Status
  /// </summary>
  public sealed partial class GossipStatus : pb::IMessage<GossipStatus> {
    private static readonly pb::MessageParser<GossipStatus> _parser = new pb::MessageParser<GossipStatus>(() => new GossipStatus());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GossipStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Protobuf.Msg.ClusterMessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GossipStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GossipStatus(GossipStatus other) : this() {
      From = other.from_ != null ? other.From.Clone() : null;
      allHashes_ = other.allHashes_.Clone();
      Version = other.version_ != null ? other.Version.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GossipStatus Clone() {
      return new GossipStatus(this);
    }

    /// <summary>Field number for the "from" field.</summary>
    public const int FromFieldNumber = 1;
    private global::Akka.Cluster.Protobuf.Msg.UniqueAddress from_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.UniqueAddress From {
      get { return from_; }
      set {
        from_ = value;
      }
    }

    /// <summary>Field number for the "allHashes" field.</summary>
    public const int AllHashesFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_allHashes_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> allHashes_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> AllHashes {
      get { return allHashes_; }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 3;
    private global::Akka.Cluster.Protobuf.Msg.VectorClock version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.VectorClock Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GossipStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GossipStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(From, other.From)) return false;
      if(!allHashes_.Equals(other.allHashes_)) return false;
      if (!object.Equals(Version, other.Version)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (from_ != null) hash ^= From.GetHashCode();
      hash ^= allHashes_.GetHashCode();
      if (version_ != null) hash ^= Version.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (from_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(From);
      }
      allHashes_.WriteTo(output, _repeated_allHashes_codec);
      if (version_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Version);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (from_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(From);
      }
      size += allHashes_.CalculateSize(_repeated_allHashes_codec);
      if (version_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Version);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GossipStatus other) {
      if (other == null) {
        return;
      }
      if (other.from_ != null) {
        if (from_ == null) {
          from_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
        }
        From.MergeFrom(other.From);
      }
      allHashes_.Add(other.allHashes_);
      if (other.version_ != null) {
        if (version_ == null) {
          version_ = new global::Akka.Cluster.Protobuf.Msg.VectorClock();
        }
        Version.MergeFrom(other.Version);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (from_ == null) {
              from_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
            }
            input.ReadMessage(from_);
            break;
          }
          case 18: {
            allHashes_.AddEntriesFrom(input, _repeated_allHashes_codec);
            break;
          }
          case 26: {
            if (version_ == null) {
              version_ = new global::Akka.Cluster.Protobuf.Msg.VectorClock();
            }
            input.ReadMessage(version_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///*
  /// Gossip
  /// </summary>
  public sealed partial class Gossip : pb::IMessage<Gossip> {
    private static readonly pb::MessageParser<Gossip> _parser = new pb::MessageParser<Gossip>(() => new Gossip());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Gossip> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Protobuf.Msg.ClusterMessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gossip() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gossip(Gossip other) : this() {
      members_ = other.members_.Clone();
      Overview = other.overview_ != null ? other.Overview.Clone() : null;
      Version = other.version_ != null ? other.Version.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gossip Clone() {
      return new Gossip(this);
    }

    /// <summary>Field number for the "members" field.</summary>
    public const int MembersFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Akka.Cluster.Protobuf.Msg.Member> _repeated_members_codec
        = pb::FieldCodec.ForMessage(10, global::Akka.Cluster.Protobuf.Msg.Member.Parser);
    private readonly pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.Member> members_ = new pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.Member>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.Member> Members {
      get { return members_; }
    }

    /// <summary>Field number for the "overview" field.</summary>
    public const int OverviewFieldNumber = 2;
    private global::Akka.Cluster.Protobuf.Msg.GossipOverview overview_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.GossipOverview Overview {
      get { return overview_; }
      set {
        overview_ = value;
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 3;
    private global::Akka.Cluster.Protobuf.Msg.VectorClock version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.VectorClock Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Gossip);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Gossip other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!members_.Equals(other.members_)) return false;
      if (!object.Equals(Overview, other.Overview)) return false;
      if (!object.Equals(Version, other.Version)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= members_.GetHashCode();
      if (overview_ != null) hash ^= Overview.GetHashCode();
      if (version_ != null) hash ^= Version.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      members_.WriteTo(output, _repeated_members_codec);
      if (overview_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Overview);
      }
      if (version_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Version);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += members_.CalculateSize(_repeated_members_codec);
      if (overview_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Overview);
      }
      if (version_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Version);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Gossip other) {
      if (other == null) {
        return;
      }
      members_.Add(other.members_);
      if (other.overview_ != null) {
        if (overview_ == null) {
          overview_ = new global::Akka.Cluster.Protobuf.Msg.GossipOverview();
        }
        Overview.MergeFrom(other.Overview);
      }
      if (other.version_ != null) {
        if (version_ == null) {
          version_ = new global::Akka.Cluster.Protobuf.Msg.VectorClock();
        }
        Version.MergeFrom(other.Version);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            members_.AddEntriesFrom(input, _repeated_members_codec);
            break;
          }
          case 18: {
            if (overview_ == null) {
              overview_ = new global::Akka.Cluster.Protobuf.Msg.GossipOverview();
            }
            input.ReadMessage(overview_);
            break;
          }
          case 26: {
            if (version_ == null) {
              version_ = new global::Akka.Cluster.Protobuf.Msg.VectorClock();
            }
            input.ReadMessage(version_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///*
  /// Gossip Overview
  /// </summary>
  public sealed partial class GossipOverview : pb::IMessage<GossipOverview> {
    private static readonly pb::MessageParser<GossipOverview> _parser = new pb::MessageParser<GossipOverview>(() => new GossipOverview());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GossipOverview> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Protobuf.Msg.ClusterMessagesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GossipOverview() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GossipOverview(GossipOverview other) : this() {
      seen_ = other.seen_.Clone();
      Reachability = other.reachability_ != null ? other.Reachability.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GossipOverview Clone() {
      return new GossipOverview(this);
    }

    /// <summary>Field number for the "seen" field.</summary>
    public const int SeenFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Akka.Cluster.Protobuf.Msg.UniqueAddress> _repeated_seen_codec
        = pb::FieldCodec.ForMessage(10, global::Akka.Cluster.Protobuf.Msg.UniqueAddress.Parser);
    private readonly pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.UniqueAddress> seen_ = new pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.UniqueAddress>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.UniqueAddress> Seen {
      get { return seen_; }
    }

    /// <summary>Field number for the "reachability" field.</summary>
    public const int ReachabilityFieldNumber = 2;
    private global::Akka.Cluster.Protobuf.Msg.Reachability reachability_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.Reachability Reachability {
      get { return reachability_; }
      set {
        reachability_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GossipOverview);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GossipOverview other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!seen_.Equals(other.seen_)) return false;
      if (!object.Equals(Reachability, other.Reachability)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= seen_.GetHashCode();
      if (reachability_ != null) hash ^= Reachability.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      seen_.WriteTo(output, _repeated_seen_codec);
      if (reachability_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Reachability);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += seen_.CalculateSize(_repeated_seen_codec);
      if (reachability_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reachability);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GossipOverview other) {
      if (other == null) {
        return;
      }
      seen_.Add(other.seen_);
      if (other.reachability_ != null) {
        if (reachability_ == null) {
          reachability_ = new global::Akka.Cluster.Protobuf.Msg.Reachability();
        }
        Reachability.MergeFrom(other.Reachability);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            seen_.AddEntriesFrom(input, _repeated_seen_codec);
            break;
          }
          case 18: {
            if (reachability_ == null) {
              reachability_ = new global::Akka.Cluster.Protobuf.Msg.Reachability();
            }
            input.ReadMessage(reachability_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///*
  /// Reachability
  /// </summary>
  public sealed partial class Reachability : pb::IMessage<Reachability> {
    private static readonly pb::MessageParser<Reachability> _parser = new pb::MessageParser<Reachability>(() => new Reachability());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Reachability> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Protobuf.Msg.ClusterMessagesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Reachability() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Reachability(Reachability other) : this() {
      records_ = other.records_.Clone();
      versions_ = other.versions_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Reachability Clone() {
      return new Reachability(this);
    }

    /// <summary>Field number for the "records" field.</summary>
    public const int RecordsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Akka.Cluster.Protobuf.Msg.Record> _repeated_records_codec
        = pb::FieldCodec.ForMessage(10, global::Akka.Cluster.Protobuf.Msg.Record.Parser);
    private readonly pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.Record> records_ = new pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.Record>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.Record> Records {
      get { return records_; }
    }

    /// <summary>Field number for the "versions" field.</summary>
    public const int VersionsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Akka.Cluster.Protobuf.Msg.Reachability.Types.ReachabilityVersion> _repeated_versions_codec
        = pb::FieldCodec.ForMessage(18, global::Akka.Cluster.Protobuf.Msg.Reachability.Types.ReachabilityVersion.Parser);
    private readonly pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.Reachability.Types.ReachabilityVersion> versions_ = new pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.Reachability.Types.ReachabilityVersion>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.Reachability.Types.ReachabilityVersion> Versions {
      get { return versions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Reachability);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Reachability other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!records_.Equals(other.records_)) return false;
      if(!versions_.Equals(other.versions_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= records_.GetHashCode();
      hash ^= versions_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      records_.WriteTo(output, _repeated_records_codec);
      versions_.WriteTo(output, _repeated_versions_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += records_.CalculateSize(_repeated_records_codec);
      size += versions_.CalculateSize(_repeated_versions_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Reachability other) {
      if (other == null) {
        return;
      }
      records_.Add(other.records_);
      versions_.Add(other.versions_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            records_.AddEntriesFrom(input, _repeated_records_codec);
            break;
          }
          case 18: {
            versions_.AddEntriesFrom(input, _repeated_versions_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Reachability message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class ReachabilityVersion : pb::IMessage<ReachabilityVersion> {
        private static readonly pb::MessageParser<ReachabilityVersion> _parser = new pb::MessageParser<ReachabilityVersion>(() => new ReachabilityVersion());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<ReachabilityVersion> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Akka.Cluster.Protobuf.Msg.Reachability.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ReachabilityVersion() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ReachabilityVersion(ReachabilityVersion other) : this() {
          UniqueAddress = other.uniqueAddress_ != null ? other.UniqueAddress.Clone() : null;
          version_ = other.version_;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ReachabilityVersion Clone() {
          return new ReachabilityVersion(this);
        }

        /// <summary>Field number for the "uniqueAddress" field.</summary>
        public const int UniqueAddressFieldNumber = 1;
        private global::Akka.Cluster.Protobuf.Msg.UniqueAddress uniqueAddress_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Akka.Cluster.Protobuf.Msg.UniqueAddress UniqueAddress {
          get { return uniqueAddress_; }
          set {
            uniqueAddress_ = value;
          }
        }

        /// <summary>Field number for the "version" field.</summary>
        public const int VersionFieldNumber = 2;
        private long version_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public long Version {
          get { return version_; }
          set {
            version_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as ReachabilityVersion);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(ReachabilityVersion other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(UniqueAddress, other.UniqueAddress)) return false;
          if (Version != other.Version) return false;
          return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (uniqueAddress_ != null) hash ^= UniqueAddress.GetHashCode();
          if (Version != 0L) hash ^= Version.GetHashCode();
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (uniqueAddress_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(UniqueAddress);
          }
          if (Version != 0L) {
            output.WriteRawTag(16);
            output.WriteInt64(Version);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (uniqueAddress_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(UniqueAddress);
          }
          if (Version != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(Version);
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(ReachabilityVersion other) {
          if (other == null) {
            return;
          }
          if (other.uniqueAddress_ != null) {
            if (uniqueAddress_ == null) {
              uniqueAddress_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
            }
            UniqueAddress.MergeFrom(other.UniqueAddress);
          }
          if (other.Version != 0L) {
            Version = other.Version;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 10: {
                if (uniqueAddress_ == null) {
                  uniqueAddress_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
                }
                input.ReadMessage(uniqueAddress_);
                break;
              }
              case 16: {
                Version = input.ReadInt64();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  public sealed partial class Record : pb::IMessage<Record> {
    private static readonly pb::MessageParser<Record> _parser = new pb::MessageParser<Record>(() => new Record());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Record> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Protobuf.Msg.ClusterMessagesReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Record() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Record(Record other) : this() {
      Observer = other.observer_ != null ? other.Observer.Clone() : null;
      Subject = other.subject_ != null ? other.Subject.Clone() : null;
      status_ = other.status_;
      version_ = other.version_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Record Clone() {
      return new Record(this);
    }

    /// <summary>Field number for the "observer" field.</summary>
    public const int ObserverFieldNumber = 1;
    private global::Akka.Cluster.Protobuf.Msg.UniqueAddress observer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.UniqueAddress Observer {
      get { return observer_; }
      set {
        observer_ = value;
      }
    }

    /// <summary>Field number for the "subject" field.</summary>
    public const int SubjectFieldNumber = 2;
    private global::Akka.Cluster.Protobuf.Msg.UniqueAddress subject_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.UniqueAddress Subject {
      get { return subject_; }
      set {
        subject_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 3;
    private global::Akka.Cluster.Protobuf.Msg.Record.Types.ReachabilityStatus status_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.Record.Types.ReachabilityStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 4;
    private long version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Record);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Record other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Observer, other.Observer)) return false;
      if (!object.Equals(Subject, other.Subject)) return false;
      if (Status != other.Status) return false;
      if (Version != other.Version) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (observer_ != null) hash ^= Observer.GetHashCode();
      if (subject_ != null) hash ^= Subject.GetHashCode();
      if (Status != 0) hash ^= Status.GetHashCode();
      if (Version != 0L) hash ^= Version.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (observer_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Observer);
      }
      if (subject_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Subject);
      }
      if (Status != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (Version != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Version);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (observer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Observer);
      }
      if (subject_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Subject);
      }
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (Version != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Version);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Record other) {
      if (other == null) {
        return;
      }
      if (other.observer_ != null) {
        if (observer_ == null) {
          observer_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
        }
        Observer.MergeFrom(other.Observer);
      }
      if (other.subject_ != null) {
        if (subject_ == null) {
          subject_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
        }
        Subject.MergeFrom(other.Subject);
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.Version != 0L) {
        Version = other.Version;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (observer_ == null) {
              observer_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
            }
            input.ReadMessage(observer_);
            break;
          }
          case 18: {
            if (subject_ == null) {
              subject_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
            }
            input.ReadMessage(subject_);
            break;
          }
          case 24: {
            status_ = (global::Akka.Cluster.Protobuf.Msg.Record.Types.ReachabilityStatus) input.ReadEnum();
            break;
          }
          case 32: {
            Version = input.ReadInt64();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Record message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum ReachabilityStatus {
        [pbr::OriginalName("Reachable")] Reachable = 0,
        [pbr::OriginalName("Unreachable")] Unreachable = 1,
        [pbr::OriginalName("Terminated")] Terminated = 2,
      }

    }
    #endregion

  }

  /// <summary>
  ///*
  /// Member
  /// </summary>
  public sealed partial class Member : pb::IMessage<Member> {
    private static readonly pb::MessageParser<Member> _parser = new pb::MessageParser<Member>(() => new Member());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Member> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Protobuf.Msg.ClusterMessagesReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Member() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Member(Member other) : this() {
      UniqueAddress = other.uniqueAddress_ != null ? other.UniqueAddress.Clone() : null;
      upNumber_ = other.upNumber_;
      status_ = other.status_;
      roles_ = other.roles_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Member Clone() {
      return new Member(this);
    }

    /// <summary>Field number for the "uniqueAddress" field.</summary>
    public const int UniqueAddressFieldNumber = 1;
    private global::Akka.Cluster.Protobuf.Msg.UniqueAddress uniqueAddress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.UniqueAddress UniqueAddress {
      get { return uniqueAddress_; }
      set {
        uniqueAddress_ = value;
      }
    }

    /// <summary>Field number for the "upNumber" field.</summary>
    public const int UpNumberFieldNumber = 2;
    private int upNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UpNumber {
      get { return upNumber_; }
      set {
        upNumber_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 3;
    private global::Akka.Cluster.Protobuf.Msg.Member.Types.MemberStatus status_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.Member.Types.MemberStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "roles" field.</summary>
    public const int RolesFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_roles_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> roles_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Roles {
      get { return roles_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Member);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Member other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UniqueAddress, other.UniqueAddress)) return false;
      if (UpNumber != other.UpNumber) return false;
      if (Status != other.Status) return false;
      if(!roles_.Equals(other.roles_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (uniqueAddress_ != null) hash ^= UniqueAddress.GetHashCode();
      if (UpNumber != 0) hash ^= UpNumber.GetHashCode();
      if (Status != 0) hash ^= Status.GetHashCode();
      hash ^= roles_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (uniqueAddress_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UniqueAddress);
      }
      if (UpNumber != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UpNumber);
      }
      if (Status != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      roles_.WriteTo(output, _repeated_roles_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (uniqueAddress_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UniqueAddress);
      }
      if (UpNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UpNumber);
      }
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      size += roles_.CalculateSize(_repeated_roles_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Member other) {
      if (other == null) {
        return;
      }
      if (other.uniqueAddress_ != null) {
        if (uniqueAddress_ == null) {
          uniqueAddress_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
        }
        UniqueAddress.MergeFrom(other.UniqueAddress);
      }
      if (other.UpNumber != 0) {
        UpNumber = other.UpNumber;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      roles_.Add(other.roles_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (uniqueAddress_ == null) {
              uniqueAddress_ = new global::Akka.Cluster.Protobuf.Msg.UniqueAddress();
            }
            input.ReadMessage(uniqueAddress_);
            break;
          }
          case 16: {
            UpNumber = input.ReadInt32();
            break;
          }
          case 24: {
            status_ = (global::Akka.Cluster.Protobuf.Msg.Member.Types.MemberStatus) input.ReadEnum();
            break;
          }
          case 34: {
            roles_.AddEntriesFrom(input, _repeated_roles_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Member message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum MemberStatus {
        [pbr::OriginalName("Joining")] Joining = 0,
        [pbr::OriginalName("Up")] Up = 1,
        [pbr::OriginalName("Leaving")] Leaving = 2,
        [pbr::OriginalName("Exiting")] Exiting = 3,
        [pbr::OriginalName("Down")] Down = 4,
        [pbr::OriginalName("Removed")] Removed = 5,
      }

    }
    #endregion

  }

  /// <summary>
  ///*
  /// Vector Clock
  /// </summary>
  public sealed partial class VectorClock : pb::IMessage<VectorClock> {
    private static readonly pb::MessageParser<VectorClock> _parser = new pb::MessageParser<VectorClock>(() => new VectorClock());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VectorClock> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Protobuf.Msg.ClusterMessagesReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VectorClock() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VectorClock(VectorClock other) : this() {
      versions_ = other.versions_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VectorClock Clone() {
      return new VectorClock(this);
    }

    /// <summary>Field number for the "versions" field.</summary>
    public const int VersionsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Akka.Cluster.Protobuf.Msg.VectorClock.Types.Version> _repeated_versions_codec
        = pb::FieldCodec.ForMessage(10, global::Akka.Cluster.Protobuf.Msg.VectorClock.Types.Version.Parser);
    private readonly pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.VectorClock.Types.Version> versions_ = new pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.VectorClock.Types.Version>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Akka.Cluster.Protobuf.Msg.VectorClock.Types.Version> Versions {
      get { return versions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VectorClock);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VectorClock other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!versions_.Equals(other.versions_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= versions_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      versions_.WriteTo(output, _repeated_versions_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += versions_.CalculateSize(_repeated_versions_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VectorClock other) {
      if (other == null) {
        return;
      }
      versions_.Add(other.versions_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            versions_.AddEntriesFrom(input, _repeated_versions_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the VectorClock message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class Version : pb::IMessage<Version> {
        private static readonly pb::MessageParser<Version> _parser = new pb::MessageParser<Version>(() => new Version());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Version> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Akka.Cluster.Protobuf.Msg.VectorClock.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Version() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Version(Version other) : this() {
          node_ = other.node_;
          timestamp_ = other.timestamp_;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Version Clone() {
          return new Version(this);
        }

        /// <summary>Field number for the "node" field.</summary>
        public const int NodeFieldNumber = 1;
        private string node_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Node {
          get { return node_; }
          set {
            node_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "timestamp" field.</summary>
        public const int TimestampFieldNumber = 2;
        private long timestamp_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public long Timestamp {
          get { return timestamp_; }
          set {
            timestamp_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Version);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Version other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Node != other.Node) return false;
          if (Timestamp != other.Timestamp) return false;
          return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Node.Length != 0) hash ^= Node.GetHashCode();
          if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Node.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Node);
          }
          if (Timestamp != 0L) {
            output.WriteRawTag(16);
            output.WriteInt64(Timestamp);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Node.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Node);
          }
          if (Timestamp != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Version other) {
          if (other == null) {
            return;
          }
          if (other.Node.Length != 0) {
            Node = other.Node;
          }
          if (other.Timestamp != 0L) {
            Timestamp = other.Timestamp;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 10: {
                Node = input.ReadString();
                break;
              }
              case 16: {
                Timestamp = input.ReadInt64();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  public sealed partial class Address : pb::IMessage<Address> {
    private static readonly pb::MessageParser<Address> _parser = new pb::MessageParser<Address>(() => new Address());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Address> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Protobuf.Msg.ClusterMessagesReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Address() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Address(Address other) : this() {
      system_ = other.system_;
      hostname_ = other.hostname_;
      port_ = other.port_;
      protocol_ = other.protocol_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Address Clone() {
      return new Address(this);
    }

    /// <summary>Field number for the "system" field.</summary>
    public const int SystemFieldNumber = 1;
    private string system_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string System {
      get { return system_; }
      set {
        system_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hostname" field.</summary>
    public const int HostnameFieldNumber = 2;
    private string hostname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Hostname {
      get { return hostname_; }
      set {
        hostname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 3;
    private int port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    /// <summary>Field number for the "protocol" field.</summary>
    public const int ProtocolFieldNumber = 4;
    private string protocol_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Protocol {
      get { return protocol_; }
      set {
        protocol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Address);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Address other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (System != other.System) return false;
      if (Hostname != other.Hostname) return false;
      if (Port != other.Port) return false;
      if (Protocol != other.Protocol) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (System.Length != 0) hash ^= System.GetHashCode();
      if (Hostname.Length != 0) hash ^= Hostname.GetHashCode();
      if (Port != 0) hash ^= Port.GetHashCode();
      if (Protocol.Length != 0) hash ^= Protocol.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (System.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(System);
      }
      if (Hostname.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Hostname);
      }
      if (Port != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Port);
      }
      if (Protocol.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Protocol);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (System.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(System);
      }
      if (Hostname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Hostname);
      }
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Port);
      }
      if (Protocol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Protocol);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Address other) {
      if (other == null) {
        return;
      }
      if (other.System.Length != 0) {
        System = other.System;
      }
      if (other.Hostname.Length != 0) {
        Hostname = other.Hostname;
      }
      if (other.Port != 0) {
        Port = other.Port;
      }
      if (other.Protocol.Length != 0) {
        Protocol = other.Protocol;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            System = input.ReadString();
            break;
          }
          case 18: {
            Hostname = input.ReadString();
            break;
          }
          case 24: {
            Port = input.ReadInt32();
            break;
          }
          case 34: {
            Protocol = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///*
  /// Defines a remote address with uid.
  /// </summary>
  public sealed partial class UniqueAddress : pb::IMessage<UniqueAddress> {
    private static readonly pb::MessageParser<UniqueAddress> _parser = new pb::MessageParser<UniqueAddress>(() => new UniqueAddress());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UniqueAddress> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Protobuf.Msg.ClusterMessagesReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UniqueAddress() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UniqueAddress(UniqueAddress other) : this() {
      Address = other.address_ != null ? other.Address.Clone() : null;
      uid_ = other.uid_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UniqueAddress Clone() {
      return new UniqueAddress(this);
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 1;
    private global::Akka.Cluster.Protobuf.Msg.Address address_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Cluster.Protobuf.Msg.Address Address {
      get { return address_; }
      set {
        address_ = value;
      }
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 2;
    private uint uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UniqueAddress);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UniqueAddress other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Address, other.Address)) return false;
      if (Uid != other.Uid) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (address_ != null) hash ^= Address.GetHashCode();
      if (Uid != 0) hash ^= Uid.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (address_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Address);
      }
      if (Uid != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Uid);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (address_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Address);
      }
      if (Uid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uid);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UniqueAddress other) {
      if (other == null) {
        return;
      }
      if (other.address_ != null) {
        if (address_ == null) {
          address_ = new global::Akka.Cluster.Protobuf.Msg.Address();
        }
        Address.MergeFrom(other.Address);
      }
      if (other.Uid != 0) {
        Uid = other.Uid;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (address_ == null) {
              address_ = new global::Akka.Cluster.Protobuf.Msg.Address();
            }
            input.ReadMessage(address_);
            break;
          }
          case 16: {
            Uid = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
