// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CoreMessages.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Akka.Protobuf.Msg {

  /// <summary>Holder for reflection information generated from CoreMessages.proto</summary>
  public static partial class CoreMessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for CoreMessages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CoreMessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJDb3JlTWVzc2FnZXMucHJvdG8SEUFra2EuUHJvdG9idWYuTXNnIlEKB1Bh",
            "eWxvYWQSFwoPZW5jbG9zZWRNZXNzYWdlGAEgASgMEhQKDHNlcmlhbGl6ZXJJ",
            "ZBgCIAEoBRIXCg9tZXNzYWdlTWFuaWZlc3QYAyABKAwiGQoJQWN0b3JQYXRo",
            "EgwKBHBhdGgYASABKAkiGAoIQWN0b3JSZWYSDAoEcGF0aBgBIAEoCSI5CghJ",
            "ZGVudGlmeRItCgltZXNzYWdlSWQYASABKAsyGi5Ba2thLlByb3RvYnVmLk1z",
            "Zy5QYXlsb2FkImwKDUFjdG9ySWRlbnRpdHkSMQoNY29ycmVsYXRpb25JZBgB",
            "IAEoCzIaLkFra2EuUHJvdG9idWYuTXNnLlBheWxvYWQSKAoDcmVmGAIgASgL",
            "MhsuQWtrYS5Qcm90b2J1Zi5Nc2cuQWN0b3JSZWYiDAoKUG9pc29uUGlsbCJj",
            "CgVXYXRjaBIsCgd3YXRjaGVlGAEgASgLMhsuQWtrYS5Qcm90b2J1Zi5Nc2cu",
            "QWN0b3JSZWYSLAoHd2F0Y2hlchgCIAEoCzIbLkFra2EuUHJvdG9idWYuTXNn",
            "LkFjdG9yUmVmImUKB1Vud2F0Y2gSLAoHd2F0Y2hlZRgBIAEoCzIbLkFra2Eu",
            "UHJvdG9idWYuTXNnLkFjdG9yUmVmEiwKB3dhdGNoZXIYAiABKAsyGy5Ba2th",
            "LlByb3RvYnVmLk1zZy5BY3RvclJlZiJ5ChZEZWF0aFdhdGNoTm90aWZpY2F0",
            "aW9uEigKA3JlZhgBIAEoCzIbLkFra2EuUHJvdG9idWYuTXNnLkFjdG9yUmVm",
            "EhoKEmV4aXN0ZW5jZUNvbmZpcm1lZBgCIAEoCBIZChFhZGRyZXNzVGVybWlu",
            "YXRlZBgDIAEoCCILCglUZXJtaW5hdGUiBgoES2lsbCJGCglTdXBlcnZpc2US",
            "KgoFY2hpbGQYASABKAsyGy5Ba2thLlByb3RvYnVmLk1zZy5BY3RvclJlZhIN",
            "CgVhc3luYxgCIAEoCCJHCgdBZGRyZXNzEhAKCHByb3RvY29sGAEgASgJEg4K",
            "BnN5c3RlbRgCIAEoCRIMCgRob3N0GAMgASgJEgwKBHBvcnQYBCABKAUiOgoL",
            "UmVtb3RlU2NvcGUSKwoHYWRkcmVzcxgBIAEoCzIaLkFra2EuUHJvdG9idWYu",
            "TXNnLkFkZHJlc3MiGAoGQ29uZmlnEg4KBmNvbmZpZxgBIAEoCSKHAQoHRGVj",
            "aWRlchIYChBkZWZhdWx0RGlyZWN0aXZlGAEgASgJEjQKBXBhaXJzGAIgAygL",
            "MiUuQWtrYS5Qcm90b2J1Zi5Nc2cuRGVjaWRlci5QYWlyc0VudHJ5GiwKClBh",
            "aXJzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASKVAQoS",
            "U3VwZXJ2aXNvclN0cmF0ZWd5EhoKEm1heE51bWJlck9mUmV0cmllcxgBIAEo",
            "BRIeChZ3aXRoaW5UaW1lTWlsbGlzZWNvbmRzGAIgASgFEisKB2RlY2lkZXIY",
            "AyABKAsyGi5Ba2thLlByb3RvYnVmLk1zZy5EZWNpZGVyEhYKDmxvZ2dpbmdF",
            "bmFibGVkGAQgASgIIgkKB1Jlc2l6ZXIi0AEKDlJvdW5kUm9iaW5Qb29sEhkK",
            "EW51bWJlck9mSW5zdGFuY2VzGAEgASgFEhkKEXVzZVBvb2xEaXNwYXRjaGVy",
            "GAIgASgIEisKB3Jlc2l6ZXIYAyABKAsyGi5Ba2thLlByb3RvYnVmLk1zZy5S",
            "ZXNpemVyEkEKEnN1cGVydmlzb3JTdHJhdGVneRgEIAEoCzIlLkFra2EuUHJv",
            "dG9idWYuTXNnLlN1cGVydmlzb3JTdHJhdGVneRIYChByb3V0ZXJEaXNwYXRj",
            "aGVyGAUgASgJIjoKD1JvdW5kUm9iaW5Hcm91cBINCgVwYXRocxgBIAMoCRIY",
            "ChByb3V0ZXJEaXNwYXRjaGVyGAIgASgJQgJIAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.Payload), global::Akka.Protobuf.Msg.Payload.Parser, new[]{ "EnclosedMessage", "SerializerId", "MessageManifest" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.ActorPath), global::Akka.Protobuf.Msg.ActorPath.Parser, new[]{ "Path" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.ActorRef), global::Akka.Protobuf.Msg.ActorRef.Parser, new[]{ "Path" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.Identify), global::Akka.Protobuf.Msg.Identify.Parser, new[]{ "MessageId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.ActorIdentity), global::Akka.Protobuf.Msg.ActorIdentity.Parser, new[]{ "CorrelationId", "Ref" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.PoisonPill), global::Akka.Protobuf.Msg.PoisonPill.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.Watch), global::Akka.Protobuf.Msg.Watch.Parser, new[]{ "Watchee", "Watcher" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.Unwatch), global::Akka.Protobuf.Msg.Unwatch.Parser, new[]{ "Watchee", "Watcher" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.DeathWatchNotification), global::Akka.Protobuf.Msg.DeathWatchNotification.Parser, new[]{ "Ref", "ExistenceConfirmed", "AddressTerminated" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.Terminate), global::Akka.Protobuf.Msg.Terminate.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.Kill), global::Akka.Protobuf.Msg.Kill.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.Supervise), global::Akka.Protobuf.Msg.Supervise.Parser, new[]{ "Child", "Async" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.Address), global::Akka.Protobuf.Msg.Address.Parser, new[]{ "Protocol", "System", "Host", "Port" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.RemoteScope), global::Akka.Protobuf.Msg.RemoteScope.Parser, new[]{ "Address" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.Config), global::Akka.Protobuf.Msg.Config.Parser, new[]{ "Config_" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.Decider), global::Akka.Protobuf.Msg.Decider.Parser, new[]{ "DefaultDirective", "Pairs" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.SupervisorStrategy), global::Akka.Protobuf.Msg.SupervisorStrategy.Parser, new[]{ "MaxNumberOfRetries", "WithinTimeMilliseconds", "Decider", "LoggingEnabled" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.Resizer), global::Akka.Protobuf.Msg.Resizer.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.RoundRobinPool), global::Akka.Protobuf.Msg.RoundRobinPool.Parser, new[]{ "NumberOfInstances", "UsePoolDispatcher", "Resizer", "SupervisorStrategy", "RouterDispatcher" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Protobuf.Msg.RoundRobinGroup), global::Akka.Protobuf.Msg.RoundRobinGroup.Parser, new[]{ "Paths", "RouterDispatcher" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Payload : pb::IMessage<Payload> {
    private static readonly pb::MessageParser<Payload> _parser = new pb::MessageParser<Payload>(() => new Payload());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Payload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Payload() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Payload(Payload other) : this() {
      enclosedMessage_ = other.enclosedMessage_;
      serializerId_ = other.serializerId_;
      messageManifest_ = other.messageManifest_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Payload Clone() {
      return new Payload(this);
    }

    /// <summary>Field number for the "enclosedMessage" field.</summary>
    public const int EnclosedMessageFieldNumber = 1;
    private pb::ByteString enclosedMessage_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString EnclosedMessage {
      get { return enclosedMessage_; }
      set {
        enclosedMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "serializerId" field.</summary>
    public const int SerializerIdFieldNumber = 2;
    private int serializerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SerializerId {
      get { return serializerId_; }
      set {
        serializerId_ = value;
      }
    }

    /// <summary>Field number for the "messageManifest" field.</summary>
    public const int MessageManifestFieldNumber = 3;
    private pb::ByteString messageManifest_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString MessageManifest {
      get { return messageManifest_; }
      set {
        messageManifest_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Payload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Payload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EnclosedMessage != other.EnclosedMessage) return false;
      if (SerializerId != other.SerializerId) return false;
      if (MessageManifest != other.MessageManifest) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (EnclosedMessage.Length != 0) hash ^= EnclosedMessage.GetHashCode();
      if (SerializerId != 0) hash ^= SerializerId.GetHashCode();
      if (MessageManifest.Length != 0) hash ^= MessageManifest.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (EnclosedMessage.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(EnclosedMessage);
      }
      if (SerializerId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SerializerId);
      }
      if (MessageManifest.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(MessageManifest);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EnclosedMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(EnclosedMessage);
      }
      if (SerializerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SerializerId);
      }
      if (MessageManifest.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(MessageManifest);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Payload other) {
      if (other == null) {
        return;
      }
      if (other.EnclosedMessage.Length != 0) {
        EnclosedMessage = other.EnclosedMessage;
      }
      if (other.SerializerId != 0) {
        SerializerId = other.SerializerId;
      }
      if (other.MessageManifest.Length != 0) {
        MessageManifest = other.MessageManifest;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            EnclosedMessage = input.ReadBytes();
            break;
          }
          case 16: {
            SerializerId = input.ReadInt32();
            break;
          }
          case 26: {
            MessageManifest = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ActorPath : pb::IMessage<ActorPath> {
    private static readonly pb::MessageParser<ActorPath> _parser = new pb::MessageParser<ActorPath>(() => new ActorPath());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ActorPath> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActorPath() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActorPath(ActorPath other) : this() {
      path_ = other.path_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActorPath Clone() {
      return new ActorPath(this);
    }

    /// <summary>Field number for the "path" field.</summary>
    public const int PathFieldNumber = 1;
    private string path_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Path {
      get { return path_; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ActorPath);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ActorPath other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Path != other.Path) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Path.Length != 0) hash ^= Path.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Path.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Path);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ActorPath other) {
      if (other == null) {
        return;
      }
      if (other.Path.Length != 0) {
        Path = other.Path;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Path = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ActorRef : pb::IMessage<ActorRef> {
    private static readonly pb::MessageParser<ActorRef> _parser = new pb::MessageParser<ActorRef>(() => new ActorRef());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ActorRef> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActorRef() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActorRef(ActorRef other) : this() {
      path_ = other.path_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActorRef Clone() {
      return new ActorRef(this);
    }

    /// <summary>Field number for the "path" field.</summary>
    public const int PathFieldNumber = 1;
    private string path_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Path {
      get { return path_; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ActorRef);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ActorRef other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Path != other.Path) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Path.Length != 0) hash ^= Path.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Path.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Path);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ActorRef other) {
      if (other == null) {
        return;
      }
      if (other.Path.Length != 0) {
        Path = other.Path;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Path = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Identify : pb::IMessage<Identify> {
    private static readonly pb::MessageParser<Identify> _parser = new pb::MessageParser<Identify>(() => new Identify());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Identify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Identify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Identify(Identify other) : this() {
      MessageId = other.messageId_ != null ? other.MessageId.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Identify Clone() {
      return new Identify(this);
    }

    /// <summary>Field number for the "messageId" field.</summary>
    public const int MessageIdFieldNumber = 1;
    private global::Akka.Protobuf.Msg.Payload messageId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Protobuf.Msg.Payload MessageId {
      get { return messageId_; }
      set {
        messageId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Identify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Identify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MessageId, other.MessageId)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (messageId_ != null) hash ^= MessageId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (messageId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MessageId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (messageId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MessageId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Identify other) {
      if (other == null) {
        return;
      }
      if (other.messageId_ != null) {
        if (messageId_ == null) {
          messageId_ = new global::Akka.Protobuf.Msg.Payload();
        }
        MessageId.MergeFrom(other.MessageId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (messageId_ == null) {
              messageId_ = new global::Akka.Protobuf.Msg.Payload();
            }
            input.ReadMessage(messageId_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ActorIdentity : pb::IMessage<ActorIdentity> {
    private static readonly pb::MessageParser<ActorIdentity> _parser = new pb::MessageParser<ActorIdentity>(() => new ActorIdentity());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ActorIdentity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActorIdentity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActorIdentity(ActorIdentity other) : this() {
      CorrelationId = other.correlationId_ != null ? other.CorrelationId.Clone() : null;
      Ref = other.ref_ != null ? other.Ref.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActorIdentity Clone() {
      return new ActorIdentity(this);
    }

    /// <summary>Field number for the "correlationId" field.</summary>
    public const int CorrelationIdFieldNumber = 1;
    private global::Akka.Protobuf.Msg.Payload correlationId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Protobuf.Msg.Payload CorrelationId {
      get { return correlationId_; }
      set {
        correlationId_ = value;
      }
    }

    /// <summary>Field number for the "ref" field.</summary>
    public const int RefFieldNumber = 2;
    private global::Akka.Protobuf.Msg.ActorRef ref_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Protobuf.Msg.ActorRef Ref {
      get { return ref_; }
      set {
        ref_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ActorIdentity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ActorIdentity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CorrelationId, other.CorrelationId)) return false;
      if (!object.Equals(Ref, other.Ref)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (correlationId_ != null) hash ^= CorrelationId.GetHashCode();
      if (ref_ != null) hash ^= Ref.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (correlationId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CorrelationId);
      }
      if (ref_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Ref);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (correlationId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CorrelationId);
      }
      if (ref_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ref);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ActorIdentity other) {
      if (other == null) {
        return;
      }
      if (other.correlationId_ != null) {
        if (correlationId_ == null) {
          correlationId_ = new global::Akka.Protobuf.Msg.Payload();
        }
        CorrelationId.MergeFrom(other.CorrelationId);
      }
      if (other.ref_ != null) {
        if (ref_ == null) {
          ref_ = new global::Akka.Protobuf.Msg.ActorRef();
        }
        Ref.MergeFrom(other.Ref);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (correlationId_ == null) {
              correlationId_ = new global::Akka.Protobuf.Msg.Payload();
            }
            input.ReadMessage(correlationId_);
            break;
          }
          case 18: {
            if (ref_ == null) {
              ref_ = new global::Akka.Protobuf.Msg.ActorRef();
            }
            input.ReadMessage(ref_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PoisonPill : pb::IMessage<PoisonPill> {
    private static readonly pb::MessageParser<PoisonPill> _parser = new pb::MessageParser<PoisonPill>(() => new PoisonPill());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PoisonPill> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PoisonPill() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PoisonPill(PoisonPill other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PoisonPill Clone() {
      return new PoisonPill(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PoisonPill);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PoisonPill other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PoisonPill other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed partial class Watch : pb::IMessage<Watch> {
    private static readonly pb::MessageParser<Watch> _parser = new pb::MessageParser<Watch>(() => new Watch());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Watch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Watch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Watch(Watch other) : this() {
      Watchee = other.watchee_ != null ? other.Watchee.Clone() : null;
      Watcher = other.watcher_ != null ? other.Watcher.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Watch Clone() {
      return new Watch(this);
    }

    /// <summary>Field number for the "watchee" field.</summary>
    public const int WatcheeFieldNumber = 1;
    private global::Akka.Protobuf.Msg.ActorRef watchee_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Protobuf.Msg.ActorRef Watchee {
      get { return watchee_; }
      set {
        watchee_ = value;
      }
    }

    /// <summary>Field number for the "watcher" field.</summary>
    public const int WatcherFieldNumber = 2;
    private global::Akka.Protobuf.Msg.ActorRef watcher_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Protobuf.Msg.ActorRef Watcher {
      get { return watcher_; }
      set {
        watcher_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Watch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Watch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Watchee, other.Watchee)) return false;
      if (!object.Equals(Watcher, other.Watcher)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (watchee_ != null) hash ^= Watchee.GetHashCode();
      if (watcher_ != null) hash ^= Watcher.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (watchee_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Watchee);
      }
      if (watcher_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Watcher);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (watchee_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Watchee);
      }
      if (watcher_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Watcher);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Watch other) {
      if (other == null) {
        return;
      }
      if (other.watchee_ != null) {
        if (watchee_ == null) {
          watchee_ = new global::Akka.Protobuf.Msg.ActorRef();
        }
        Watchee.MergeFrom(other.Watchee);
      }
      if (other.watcher_ != null) {
        if (watcher_ == null) {
          watcher_ = new global::Akka.Protobuf.Msg.ActorRef();
        }
        Watcher.MergeFrom(other.Watcher);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (watchee_ == null) {
              watchee_ = new global::Akka.Protobuf.Msg.ActorRef();
            }
            input.ReadMessage(watchee_);
            break;
          }
          case 18: {
            if (watcher_ == null) {
              watcher_ = new global::Akka.Protobuf.Msg.ActorRef();
            }
            input.ReadMessage(watcher_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Unwatch : pb::IMessage<Unwatch> {
    private static readonly pb::MessageParser<Unwatch> _parser = new pb::MessageParser<Unwatch>(() => new Unwatch());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Unwatch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Unwatch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Unwatch(Unwatch other) : this() {
      Watchee = other.watchee_ != null ? other.Watchee.Clone() : null;
      Watcher = other.watcher_ != null ? other.Watcher.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Unwatch Clone() {
      return new Unwatch(this);
    }

    /// <summary>Field number for the "watchee" field.</summary>
    public const int WatcheeFieldNumber = 1;
    private global::Akka.Protobuf.Msg.ActorRef watchee_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Protobuf.Msg.ActorRef Watchee {
      get { return watchee_; }
      set {
        watchee_ = value;
      }
    }

    /// <summary>Field number for the "watcher" field.</summary>
    public const int WatcherFieldNumber = 2;
    private global::Akka.Protobuf.Msg.ActorRef watcher_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Protobuf.Msg.ActorRef Watcher {
      get { return watcher_; }
      set {
        watcher_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Unwatch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Unwatch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Watchee, other.Watchee)) return false;
      if (!object.Equals(Watcher, other.Watcher)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (watchee_ != null) hash ^= Watchee.GetHashCode();
      if (watcher_ != null) hash ^= Watcher.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (watchee_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Watchee);
      }
      if (watcher_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Watcher);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (watchee_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Watchee);
      }
      if (watcher_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Watcher);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Unwatch other) {
      if (other == null) {
        return;
      }
      if (other.watchee_ != null) {
        if (watchee_ == null) {
          watchee_ = new global::Akka.Protobuf.Msg.ActorRef();
        }
        Watchee.MergeFrom(other.Watchee);
      }
      if (other.watcher_ != null) {
        if (watcher_ == null) {
          watcher_ = new global::Akka.Protobuf.Msg.ActorRef();
        }
        Watcher.MergeFrom(other.Watcher);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (watchee_ == null) {
              watchee_ = new global::Akka.Protobuf.Msg.ActorRef();
            }
            input.ReadMessage(watchee_);
            break;
          }
          case 18: {
            if (watcher_ == null) {
              watcher_ = new global::Akka.Protobuf.Msg.ActorRef();
            }
            input.ReadMessage(watcher_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class DeathWatchNotification : pb::IMessage<DeathWatchNotification> {
    private static readonly pb::MessageParser<DeathWatchNotification> _parser = new pb::MessageParser<DeathWatchNotification>(() => new DeathWatchNotification());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeathWatchNotification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeathWatchNotification() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeathWatchNotification(DeathWatchNotification other) : this() {
      Ref = other.ref_ != null ? other.Ref.Clone() : null;
      existenceConfirmed_ = other.existenceConfirmed_;
      addressTerminated_ = other.addressTerminated_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeathWatchNotification Clone() {
      return new DeathWatchNotification(this);
    }

    /// <summary>Field number for the "ref" field.</summary>
    public const int RefFieldNumber = 1;
    private global::Akka.Protobuf.Msg.ActorRef ref_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Protobuf.Msg.ActorRef Ref {
      get { return ref_; }
      set {
        ref_ = value;
      }
    }

    /// <summary>Field number for the "existenceConfirmed" field.</summary>
    public const int ExistenceConfirmedFieldNumber = 2;
    private bool existenceConfirmed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ExistenceConfirmed {
      get { return existenceConfirmed_; }
      set {
        existenceConfirmed_ = value;
      }
    }

    /// <summary>Field number for the "addressTerminated" field.</summary>
    public const int AddressTerminatedFieldNumber = 3;
    private bool addressTerminated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool AddressTerminated {
      get { return addressTerminated_; }
      set {
        addressTerminated_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeathWatchNotification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeathWatchNotification other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Ref, other.Ref)) return false;
      if (ExistenceConfirmed != other.ExistenceConfirmed) return false;
      if (AddressTerminated != other.AddressTerminated) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ref_ != null) hash ^= Ref.GetHashCode();
      if (ExistenceConfirmed != false) hash ^= ExistenceConfirmed.GetHashCode();
      if (AddressTerminated != false) hash ^= AddressTerminated.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ref_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Ref);
      }
      if (ExistenceConfirmed != false) {
        output.WriteRawTag(16);
        output.WriteBool(ExistenceConfirmed);
      }
      if (AddressTerminated != false) {
        output.WriteRawTag(24);
        output.WriteBool(AddressTerminated);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ref_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ref);
      }
      if (ExistenceConfirmed != false) {
        size += 1 + 1;
      }
      if (AddressTerminated != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeathWatchNotification other) {
      if (other == null) {
        return;
      }
      if (other.ref_ != null) {
        if (ref_ == null) {
          ref_ = new global::Akka.Protobuf.Msg.ActorRef();
        }
        Ref.MergeFrom(other.Ref);
      }
      if (other.ExistenceConfirmed != false) {
        ExistenceConfirmed = other.ExistenceConfirmed;
      }
      if (other.AddressTerminated != false) {
        AddressTerminated = other.AddressTerminated;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (ref_ == null) {
              ref_ = new global::Akka.Protobuf.Msg.ActorRef();
            }
            input.ReadMessage(ref_);
            break;
          }
          case 16: {
            ExistenceConfirmed = input.ReadBool();
            break;
          }
          case 24: {
            AddressTerminated = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Terminate : pb::IMessage<Terminate> {
    private static readonly pb::MessageParser<Terminate> _parser = new pb::MessageParser<Terminate>(() => new Terminate());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Terminate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Terminate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Terminate(Terminate other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Terminate Clone() {
      return new Terminate(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Terminate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Terminate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Terminate other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed partial class Kill : pb::IMessage<Kill> {
    private static readonly pb::MessageParser<Kill> _parser = new pb::MessageParser<Kill>(() => new Kill());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Kill> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Kill() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Kill(Kill other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Kill Clone() {
      return new Kill(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Kill);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Kill other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Kill other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed partial class Supervise : pb::IMessage<Supervise> {
    private static readonly pb::MessageParser<Supervise> _parser = new pb::MessageParser<Supervise>(() => new Supervise());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Supervise> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Supervise() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Supervise(Supervise other) : this() {
      Child = other.child_ != null ? other.Child.Clone() : null;
      async_ = other.async_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Supervise Clone() {
      return new Supervise(this);
    }

    /// <summary>Field number for the "child" field.</summary>
    public const int ChildFieldNumber = 1;
    private global::Akka.Protobuf.Msg.ActorRef child_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Protobuf.Msg.ActorRef Child {
      get { return child_; }
      set {
        child_ = value;
      }
    }

    /// <summary>Field number for the "async" field.</summary>
    public const int AsyncFieldNumber = 2;
    private bool async_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Async {
      get { return async_; }
      set {
        async_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Supervise);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Supervise other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Child, other.Child)) return false;
      if (Async != other.Async) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (child_ != null) hash ^= Child.GetHashCode();
      if (Async != false) hash ^= Async.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (child_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Child);
      }
      if (Async != false) {
        output.WriteRawTag(16);
        output.WriteBool(Async);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (child_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Child);
      }
      if (Async != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Supervise other) {
      if (other == null) {
        return;
      }
      if (other.child_ != null) {
        if (child_ == null) {
          child_ = new global::Akka.Protobuf.Msg.ActorRef();
        }
        Child.MergeFrom(other.Child);
      }
      if (other.Async != false) {
        Async = other.Async;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (child_ == null) {
              child_ = new global::Akka.Protobuf.Msg.ActorRef();
            }
            input.ReadMessage(child_);
            break;
          }
          case 16: {
            Async = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Address : pb::IMessage<Address> {
    private static readonly pb::MessageParser<Address> _parser = new pb::MessageParser<Address>(() => new Address());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Address> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Address() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Address(Address other) : this() {
      protocol_ = other.protocol_;
      system_ = other.system_;
      host_ = other.host_;
      port_ = other.port_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Address Clone() {
      return new Address(this);
    }

    /// <summary>Field number for the "protocol" field.</summary>
    public const int ProtocolFieldNumber = 1;
    private string protocol_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Protocol {
      get { return protocol_; }
      set {
        protocol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "system" field.</summary>
    public const int SystemFieldNumber = 2;
    private string system_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string System {
      get { return system_; }
      set {
        system_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "host" field.</summary>
    public const int HostFieldNumber = 3;
    private string host_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Host {
      get { return host_; }
      set {
        host_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 4;
    private int port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Address);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Address other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Protocol != other.Protocol) return false;
      if (System != other.System) return false;
      if (Host != other.Host) return false;
      if (Port != other.Port) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Protocol.Length != 0) hash ^= Protocol.GetHashCode();
      if (System.Length != 0) hash ^= System.GetHashCode();
      if (Host.Length != 0) hash ^= Host.GetHashCode();
      if (Port != 0) hash ^= Port.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Protocol.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Protocol);
      }
      if (System.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(System);
      }
      if (Host.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Host);
      }
      if (Port != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Port);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Protocol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Protocol);
      }
      if (System.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(System);
      }
      if (Host.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Host);
      }
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Port);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Address other) {
      if (other == null) {
        return;
      }
      if (other.Protocol.Length != 0) {
        Protocol = other.Protocol;
      }
      if (other.System.Length != 0) {
        System = other.System;
      }
      if (other.Host.Length != 0) {
        Host = other.Host;
      }
      if (other.Port != 0) {
        Port = other.Port;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Protocol = input.ReadString();
            break;
          }
          case 18: {
            System = input.ReadString();
            break;
          }
          case 26: {
            Host = input.ReadString();
            break;
          }
          case 32: {
            Port = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RemoteScope : pb::IMessage<RemoteScope> {
    private static readonly pb::MessageParser<RemoteScope> _parser = new pb::MessageParser<RemoteScope>(() => new RemoteScope());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RemoteScope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[13]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoteScope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoteScope(RemoteScope other) : this() {
      Address = other.address_ != null ? other.Address.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoteScope Clone() {
      return new RemoteScope(this);
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 1;
    private global::Akka.Protobuf.Msg.Address address_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Protobuf.Msg.Address Address {
      get { return address_; }
      set {
        address_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RemoteScope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RemoteScope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Address, other.Address)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (address_ != null) hash ^= Address.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (address_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Address);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (address_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Address);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RemoteScope other) {
      if (other == null) {
        return;
      }
      if (other.address_ != null) {
        if (address_ == null) {
          address_ = new global::Akka.Protobuf.Msg.Address();
        }
        Address.MergeFrom(other.Address);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (address_ == null) {
              address_ = new global::Akka.Protobuf.Msg.Address();
            }
            input.ReadMessage(address_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Config : pb::IMessage<Config> {
    private static readonly pb::MessageParser<Config> _parser = new pb::MessageParser<Config>(() => new Config());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[14]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config(Config other) : this() {
      config_ = other.config_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config Clone() {
      return new Config(this);
    }

    /// <summary>Field number for the "config" field.</summary>
    public const int Config_FieldNumber = 1;
    private string config_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Config_ {
      get { return config_; }
      set {
        config_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Config_ != other.Config_) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Config_.Length != 0) hash ^= Config_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Config_.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Config_);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Config_.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Config_);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Config other) {
      if (other == null) {
        return;
      }
      if (other.Config_.Length != 0) {
        Config_ = other.Config_;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Config_ = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Decider : pb::IMessage<Decider> {
    private static readonly pb::MessageParser<Decider> _parser = new pb::MessageParser<Decider>(() => new Decider());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Decider> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[15]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Decider() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Decider(Decider other) : this() {
      defaultDirective_ = other.defaultDirective_;
      pairs_ = other.pairs_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Decider Clone() {
      return new Decider(this);
    }

    /// <summary>Field number for the "defaultDirective" field.</summary>
    public const int DefaultDirectiveFieldNumber = 1;
    private string defaultDirective_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DefaultDirective {
      get { return defaultDirective_; }
      set {
        defaultDirective_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pairs" field.</summary>
    public const int PairsFieldNumber = 2;
    private static readonly pbc::MapField<string, string>.Codec _map_pairs_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 18);
    private readonly pbc::MapField<string, string> pairs_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Pairs {
      get { return pairs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Decider);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Decider other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DefaultDirective != other.DefaultDirective) return false;
      if (!Pairs.Equals(other.Pairs)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DefaultDirective.Length != 0) hash ^= DefaultDirective.GetHashCode();
      hash ^= Pairs.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DefaultDirective.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DefaultDirective);
      }
      pairs_.WriteTo(output, _map_pairs_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DefaultDirective.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DefaultDirective);
      }
      size += pairs_.CalculateSize(_map_pairs_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Decider other) {
      if (other == null) {
        return;
      }
      if (other.DefaultDirective.Length != 0) {
        DefaultDirective = other.DefaultDirective;
      }
      pairs_.Add(other.pairs_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            DefaultDirective = input.ReadString();
            break;
          }
          case 18: {
            pairs_.AddEntriesFrom(input, _map_pairs_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SupervisorStrategy : pb::IMessage<SupervisorStrategy> {
    private static readonly pb::MessageParser<SupervisorStrategy> _parser = new pb::MessageParser<SupervisorStrategy>(() => new SupervisorStrategy());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SupervisorStrategy> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[16]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SupervisorStrategy() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SupervisorStrategy(SupervisorStrategy other) : this() {
      maxNumberOfRetries_ = other.maxNumberOfRetries_;
      withinTimeMilliseconds_ = other.withinTimeMilliseconds_;
      Decider = other.decider_ != null ? other.Decider.Clone() : null;
      loggingEnabled_ = other.loggingEnabled_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SupervisorStrategy Clone() {
      return new SupervisorStrategy(this);
    }

    /// <summary>Field number for the "maxNumberOfRetries" field.</summary>
    public const int MaxNumberOfRetriesFieldNumber = 1;
    private int maxNumberOfRetries_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxNumberOfRetries {
      get { return maxNumberOfRetries_; }
      set {
        maxNumberOfRetries_ = value;
      }
    }

    /// <summary>Field number for the "withinTimeMilliseconds" field.</summary>
    public const int WithinTimeMillisecondsFieldNumber = 2;
    private int withinTimeMilliseconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int WithinTimeMilliseconds {
      get { return withinTimeMilliseconds_; }
      set {
        withinTimeMilliseconds_ = value;
      }
    }

    /// <summary>Field number for the "decider" field.</summary>
    public const int DeciderFieldNumber = 3;
    private global::Akka.Protobuf.Msg.Decider decider_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Protobuf.Msg.Decider Decider {
      get { return decider_; }
      set {
        decider_ = value;
      }
    }

    /// <summary>Field number for the "loggingEnabled" field.</summary>
    public const int LoggingEnabledFieldNumber = 4;
    private bool loggingEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool LoggingEnabled {
      get { return loggingEnabled_; }
      set {
        loggingEnabled_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SupervisorStrategy);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SupervisorStrategy other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MaxNumberOfRetries != other.MaxNumberOfRetries) return false;
      if (WithinTimeMilliseconds != other.WithinTimeMilliseconds) return false;
      if (!object.Equals(Decider, other.Decider)) return false;
      if (LoggingEnabled != other.LoggingEnabled) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MaxNumberOfRetries != 0) hash ^= MaxNumberOfRetries.GetHashCode();
      if (WithinTimeMilliseconds != 0) hash ^= WithinTimeMilliseconds.GetHashCode();
      if (decider_ != null) hash ^= Decider.GetHashCode();
      if (LoggingEnabled != false) hash ^= LoggingEnabled.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MaxNumberOfRetries != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MaxNumberOfRetries);
      }
      if (WithinTimeMilliseconds != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(WithinTimeMilliseconds);
      }
      if (decider_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Decider);
      }
      if (LoggingEnabled != false) {
        output.WriteRawTag(32);
        output.WriteBool(LoggingEnabled);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MaxNumberOfRetries != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxNumberOfRetries);
      }
      if (WithinTimeMilliseconds != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WithinTimeMilliseconds);
      }
      if (decider_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Decider);
      }
      if (LoggingEnabled != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SupervisorStrategy other) {
      if (other == null) {
        return;
      }
      if (other.MaxNumberOfRetries != 0) {
        MaxNumberOfRetries = other.MaxNumberOfRetries;
      }
      if (other.WithinTimeMilliseconds != 0) {
        WithinTimeMilliseconds = other.WithinTimeMilliseconds;
      }
      if (other.decider_ != null) {
        if (decider_ == null) {
          decider_ = new global::Akka.Protobuf.Msg.Decider();
        }
        Decider.MergeFrom(other.Decider);
      }
      if (other.LoggingEnabled != false) {
        LoggingEnabled = other.LoggingEnabled;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            MaxNumberOfRetries = input.ReadInt32();
            break;
          }
          case 16: {
            WithinTimeMilliseconds = input.ReadInt32();
            break;
          }
          case 26: {
            if (decider_ == null) {
              decider_ = new global::Akka.Protobuf.Msg.Decider();
            }
            input.ReadMessage(decider_);
            break;
          }
          case 32: {
            LoggingEnabled = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Resizer : pb::IMessage<Resizer> {
    private static readonly pb::MessageParser<Resizer> _parser = new pb::MessageParser<Resizer>(() => new Resizer());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Resizer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[17]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resizer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resizer(Resizer other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resizer Clone() {
      return new Resizer(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Resizer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Resizer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Resizer other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed partial class RoundRobinPool : pb::IMessage<RoundRobinPool> {
    private static readonly pb::MessageParser<RoundRobinPool> _parser = new pb::MessageParser<RoundRobinPool>(() => new RoundRobinPool());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RoundRobinPool> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[18]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoundRobinPool() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoundRobinPool(RoundRobinPool other) : this() {
      numberOfInstances_ = other.numberOfInstances_;
      usePoolDispatcher_ = other.usePoolDispatcher_;
      Resizer = other.resizer_ != null ? other.Resizer.Clone() : null;
      SupervisorStrategy = other.supervisorStrategy_ != null ? other.SupervisorStrategy.Clone() : null;
      routerDispatcher_ = other.routerDispatcher_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoundRobinPool Clone() {
      return new RoundRobinPool(this);
    }

    /// <summary>Field number for the "numberOfInstances" field.</summary>
    public const int NumberOfInstancesFieldNumber = 1;
    private int numberOfInstances_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NumberOfInstances {
      get { return numberOfInstances_; }
      set {
        numberOfInstances_ = value;
      }
    }

    /// <summary>Field number for the "usePoolDispatcher" field.</summary>
    public const int UsePoolDispatcherFieldNumber = 2;
    private bool usePoolDispatcher_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool UsePoolDispatcher {
      get { return usePoolDispatcher_; }
      set {
        usePoolDispatcher_ = value;
      }
    }

    /// <summary>Field number for the "resizer" field.</summary>
    public const int ResizerFieldNumber = 3;
    private global::Akka.Protobuf.Msg.Resizer resizer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Protobuf.Msg.Resizer Resizer {
      get { return resizer_; }
      set {
        resizer_ = value;
      }
    }

    /// <summary>Field number for the "supervisorStrategy" field.</summary>
    public const int SupervisorStrategyFieldNumber = 4;
    private global::Akka.Protobuf.Msg.SupervisorStrategy supervisorStrategy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Protobuf.Msg.SupervisorStrategy SupervisorStrategy {
      get { return supervisorStrategy_; }
      set {
        supervisorStrategy_ = value;
      }
    }

    /// <summary>Field number for the "routerDispatcher" field.</summary>
    public const int RouterDispatcherFieldNumber = 5;
    private string routerDispatcher_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RouterDispatcher {
      get { return routerDispatcher_; }
      set {
        routerDispatcher_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RoundRobinPool);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RoundRobinPool other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumberOfInstances != other.NumberOfInstances) return false;
      if (UsePoolDispatcher != other.UsePoolDispatcher) return false;
      if (!object.Equals(Resizer, other.Resizer)) return false;
      if (!object.Equals(SupervisorStrategy, other.SupervisorStrategy)) return false;
      if (RouterDispatcher != other.RouterDispatcher) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NumberOfInstances != 0) hash ^= NumberOfInstances.GetHashCode();
      if (UsePoolDispatcher != false) hash ^= UsePoolDispatcher.GetHashCode();
      if (resizer_ != null) hash ^= Resizer.GetHashCode();
      if (supervisorStrategy_ != null) hash ^= SupervisorStrategy.GetHashCode();
      if (RouterDispatcher.Length != 0) hash ^= RouterDispatcher.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NumberOfInstances != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(NumberOfInstances);
      }
      if (UsePoolDispatcher != false) {
        output.WriteRawTag(16);
        output.WriteBool(UsePoolDispatcher);
      }
      if (resizer_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Resizer);
      }
      if (supervisorStrategy_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SupervisorStrategy);
      }
      if (RouterDispatcher.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(RouterDispatcher);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NumberOfInstances != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberOfInstances);
      }
      if (UsePoolDispatcher != false) {
        size += 1 + 1;
      }
      if (resizer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Resizer);
      }
      if (supervisorStrategy_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SupervisorStrategy);
      }
      if (RouterDispatcher.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RouterDispatcher);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RoundRobinPool other) {
      if (other == null) {
        return;
      }
      if (other.NumberOfInstances != 0) {
        NumberOfInstances = other.NumberOfInstances;
      }
      if (other.UsePoolDispatcher != false) {
        UsePoolDispatcher = other.UsePoolDispatcher;
      }
      if (other.resizer_ != null) {
        if (resizer_ == null) {
          resizer_ = new global::Akka.Protobuf.Msg.Resizer();
        }
        Resizer.MergeFrom(other.Resizer);
      }
      if (other.supervisorStrategy_ != null) {
        if (supervisorStrategy_ == null) {
          supervisorStrategy_ = new global::Akka.Protobuf.Msg.SupervisorStrategy();
        }
        SupervisorStrategy.MergeFrom(other.SupervisorStrategy);
      }
      if (other.RouterDispatcher.Length != 0) {
        RouterDispatcher = other.RouterDispatcher;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            NumberOfInstances = input.ReadInt32();
            break;
          }
          case 16: {
            UsePoolDispatcher = input.ReadBool();
            break;
          }
          case 26: {
            if (resizer_ == null) {
              resizer_ = new global::Akka.Protobuf.Msg.Resizer();
            }
            input.ReadMessage(resizer_);
            break;
          }
          case 34: {
            if (supervisorStrategy_ == null) {
              supervisorStrategy_ = new global::Akka.Protobuf.Msg.SupervisorStrategy();
            }
            input.ReadMessage(supervisorStrategy_);
            break;
          }
          case 42: {
            RouterDispatcher = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RoundRobinGroup : pb::IMessage<RoundRobinGroup> {
    private static readonly pb::MessageParser<RoundRobinGroup> _parser = new pb::MessageParser<RoundRobinGroup>(() => new RoundRobinGroup());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RoundRobinGroup> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Protobuf.Msg.CoreMessagesReflection.Descriptor.MessageTypes[19]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoundRobinGroup() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoundRobinGroup(RoundRobinGroup other) : this() {
      paths_ = other.paths_.Clone();
      routerDispatcher_ = other.routerDispatcher_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoundRobinGroup Clone() {
      return new RoundRobinGroup(this);
    }

    /// <summary>Field number for the "paths" field.</summary>
    public const int PathsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_paths_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> paths_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Paths {
      get { return paths_; }
    }

    /// <summary>Field number for the "routerDispatcher" field.</summary>
    public const int RouterDispatcherFieldNumber = 2;
    private string routerDispatcher_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RouterDispatcher {
      get { return routerDispatcher_; }
      set {
        routerDispatcher_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RoundRobinGroup);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RoundRobinGroup other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!paths_.Equals(other.paths_)) return false;
      if (RouterDispatcher != other.RouterDispatcher) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= paths_.GetHashCode();
      if (RouterDispatcher.Length != 0) hash ^= RouterDispatcher.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      paths_.WriteTo(output, _repeated_paths_codec);
      if (RouterDispatcher.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RouterDispatcher);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += paths_.CalculateSize(_repeated_paths_codec);
      if (RouterDispatcher.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RouterDispatcher);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RoundRobinGroup other) {
      if (other == null) {
        return;
      }
      paths_.Add(other.paths_);
      if (other.RouterDispatcher.Length != 0) {
        RouterDispatcher = other.RouterDispatcher;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            paths_.AddEntriesFrom(input, _repeated_paths_codec);
            break;
          }
          case 18: {
            RouterDispatcher = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
